apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: knative-appconfig
spec:
  components:
    - componentName: knative-configuration
      traits:
        - trait:
            apiVersion: serving.knative.dev/v1
            kind: Route
            metadata:
              name: blue-green-demo # The name of our route; appears in the URL to access the app
              namespace: default # The namespace we're working in; also appears in the URL to access the app
            spec:
              traffic:
                - revisionName: blue-green-demo-lstjm
                  percent: 100 # All traffic goes to this revision
